---
# tasks file for ./roles/apache-install-linux
- name: Instalacion de Apache
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ distribucion[ansible_facts['os_family']] }}"

- name: Firewall RedHat
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - http
    - https  
  when: ansible_facts['os_family'] == "RedHat"

- name: Firewall Debian
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    state: enabled
  loop:
    - '80'
    - '443'
  when: ansible_facts['os_family'] == "Debian"

- name: Enable proxy and proxy_balancer modules Debian
  apache2_module:
    name: proxy
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Start and enable Apache
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ distribucion[ansible_facts['os_family']] }}"
