---
# tasks file for ./roles/apache-install-linux
- name: Instalacion de Apache
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ distribucion[ansible_facts['os_family']] }}"

- name: Firewall RedHat
  firewalld:
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop:
    - http
    - https  
  when: ansible_facts['os_family'] == "RedHat"

- name: Firewall Debian
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    state: enabled
  loop:
    - '80'
    - '443'
  when: ansible_facts['os_family'] == "Debian"

- name: Start and enable apache RedHat
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "RedHat"

- name: Start and enable apache Debian
  service:
    name: apache2
    state: started
    enabled: yes
  when: ansible_facts['os_family'] == "Debian"
  
